# Generated by Django 4.1.4 on 2022-12-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('SURNAME', models.CharField(max_length=15)),
            ],
        ),
    ]
